version: "3.0"
services:
  dockerapp:
    image: henryfbp/dockerapp
    ports:
      - "4000:5000" # use port 4000 externally
    depends_on:
      - redis
    deploy:
      replicas: 2
  redis:
    image: redis:3.2.0
